// Generated by scripts/name-frames.mjs from assets/main-Dmm4WyhJ.css. Do not edit by hand.
import type { NameFrameSlices } from "./types";

export const NAME_FRAME_SLICES: Record<string, NameFrameSlices> = {
  celestial_star: { slice: [13, 54, 17, 54], width: [13, 54, 17, 54], gemWidth: 7 },
  seraph_wings: { slice: [15, 63, 13, 63], width: [15, 63, 13, 63], gemWidth: 16 },
  verdant_vine: { slice: [9, 51, 9, 54], width: [9, 51, 9, 54], gemWidth: 8 },
  clockwork_brass: { slice: [8, 38, 10, 47], width: [8, 38, 10, 47], gemWidth: 5 },
  dream_cloud: { slice: [10, 53, 12, 59], width: [10, 53, 12, 59], gemWidth: 9 },
  crimson_demon: { slice: [13, 68, 12, 68], width: [13, 68, 12, 68], gemWidth: 5 },
  violet_eclipse: { slice: [8, 61, 10, 61], width: [8, 61, 10, 61], gemWidth: 5 },
  aqua_tide: { slice: [12, 69, 9, 70], width: [12, 69, 9, 70], gemWidth: 7 },
  sakura_bloom: { slice: [9, 56, 8, 56], width: [9, 56, 8, 56], gemWidth: 5 },
  royal_crimson: { slice: [8, 51, 12, 51], width: [8, 51, 12, 51], gemWidth: 4 },
};
