// Generated by scripts/name-frames.mjs from assets/main-CItcKVbP.css. Do not edit by hand.
import type { NameFrameSlices } from "./types";

export const NAME_FRAME_SLICES: Record<string, NameFrameSlices> = {
  celestial_star: { slice: [41, 166, 50, 168], width: [1.435, 5.81, 1.75, 5.88], gemWidth: 0.735 },
  seraph_wings: { slice: [46, 193, 39, 193], width: [1.61, 6.755, 1.365, 6.755], gemWidth: 1.75 },
  verdant_vine: { slice: [28, 158, 26, 166], width: [0.98, 5.53, 0.91, 5.81], gemWidth: 0.84 },
  clockwork_brass: { slice: [26, 116, 30, 145], width: [0.91, 4.06, 1.05, 5.075], gemWidth: 0.525 },
  dream_cloud: { slice: [31, 164, 37, 183], width: [1.085, 5.74, 1.295, 6.405], gemWidth: 1.015 },
  crimson_demon: { slice: [40, 209, 36, 209], width: [1.4, 7.315, 1.26, 7.315], gemWidth: 0.56 },
  violet_eclipse: { slice: [26, 189, 31, 187], width: [0.91, 6.615, 1.085, 6.545], gemWidth: 0.56 },
  aqua_tide: { slice: [36, 212, 29, 217], width: [1.26, 7.42, 1.015, 7.595], gemWidth: 0.735 },
  sakura_bloom: { slice: [27, 174, 27, 172], width: [0.945, 6.09, 0.945, 6.02], gemWidth: 0.525 },
  royal_crimson: { slice: [25, 156, 38, 156], width: [0.875, 5.46, 1.33, 5.46], gemWidth: 0.49 },
};
