// Generated by scripts/riding-code.mjs from assets/main-DsghcYoe.js and assets/reactions-xh6aaXs0.js. Do not edit by hand.
// Not bundled: the game's riding code and what it reads, for src/game/riding.ts to follow.
const Gr = e=>typeof e=="string"&&Object.hasOwn(Qe,e);
function uK(e,i){const u=ag(i);if(e.textures.exists(u))return!0;if(Gr(i)){const[x,S]=tm[i].cell;Ph(e,u,E=>E.spritesheet(u,$9(i),{frameWidth:x,frameHeight:S}))}return!1}
const tm = {}; // the mount table, which cosmetics.json carries
const E5 = {"north-west":"north-east",west:"east","south-west":"south-east"};
const KG = ["south","south-east","east","north-east","north"];
const gf = 6;
const T5 = 16;
const ag = e=>"mount-"+e;
function to(e,i){let u=TC.get(e);u||TC.set(e,u=new Map);let x=u.get(i);if(x===void 0){for(x=0;e.has(`${i}${x}`);)x++;u.set(i,x)}return x}
const YG = 3;
class Rider {
  drawRiding(i,u,x,S){const E=this.mount,o=this.sprite.scene;if(this.riding=!!E&&Gr(E)&&!this.dead&&uK(o,E),!this.riding||!E||!Gr(E)){this.mountSprite?.visible&&this.mountSprite.setVisible(!1);for(const w of this.mountAuraParts())w.setVisible(!1);return this.shadowScaled&&(this.shadow.setScale(1),this.shadowScaled=!1),!1}const b=tm[E],[t,r]=b.cell,v=o.time.now,h=E5[this.direction]??this.direction,a=Math.max(0,KG.indexOf(h)),s=!!E5[this.direction],n=Math.floor((v+this.mountSeed)/(i?75:140)),d=a*gf+n%gf;this.flightSound(E,i,n,u,x,S.visible);const c=x+9-T5-Math.round(Math.sin((v+this.mountSeed)/420)*2),l=this.mountSprite??=o.add.sprite(u,c,ag(E),0).setOrigin(.5,1);l.texture.key!==ag(E)&&l.setTexture(ag(E)),l.depth!==S.y-2.5&&l.setDepth(S.y-2.5),l.setFrame(d).setFlipX(s).setPosition(u,c).setVisible(S.visible).setAlpha(this.sprite.alpha),this.drawMountAura(E,l,i,v,S);const[f,g]=b.seat[h],p=u-Math.floor(t/2),m=this.sprite.texture,y=to(m,`sit/${this.direction}/`);if(y)this.sprite.setFrame(`sit/${this.direction}/${y-1}`);else{const w=to(m,`pickup/${this.direction}/`);w&&this.sprite.setFrame(`pickup/${this.direction}/${Math.floor(w/2)}`)}return this.sprite.setPosition(p+(s?t-1-f:f),c-r+g+YG),this.shadowScaled||(this.shadow.setScale(2.4,1.8),this.shadowScaled=!0),!0}
}
