// Generated by scripts/riding-code.mjs from assets/main-BF6BmMX2.js and assets/reactions-SB_54ziZ.js. Do not edit by hand.
// Not bundled: the game's riding code and what it reads, for src/game/riding.ts to follow.
const Go = e=>typeof e=="string"&&Object.hasOwn(jt,e);
function Oj(e,i){const c=Xv(i);if(e.textures.exists(c))return!0;if(Go(i)){const[x,S]=Ky[i].cell;Th(e,c,E=>E.spritesheet(c,DP(i),{frameWidth:x,frameHeight:S}))}return!1}
const Ky = {}; // the mount table, which cosmetics.json carries
const L4 = {"north-west":"north-east",west:"east","south-west":"south-east"};
const FN = ["south","south-east","east","north-east","north"];
const P4 = 6;
const kN = 16;
const Xv = e=>"mount-"+e;
function Zr(e,i){let c=EM.get(e);c||EM.set(e,c=new Map);let x=c.get(i);if(x===void 0){for(x=0;e.has(`${i}${x}`);)x++;c.set(i,x)}return x}
const ON = 3;
class Rider {
  drawRiding(i,c,x,S){const E=this.mount,r=this.sprite.scene;if(this.riding=!!E&&Go(E)&&!this.dead&&Oj(r,E),!this.riding||!E||!Go(E))return this.mountSprite?.visible&&this.mountSprite.setVisible(!1),this.shadowScaled&&(this.shadow.setScale(1),this.shadowScaled=!1),!1;const b=Ky[E],[t,o]=b.cell,g=r.time.now,h=L4[this.direction]??this.direction,a=Math.max(0,FN.indexOf(h)),n=!!L4[this.direction],s=a*P4+Math.floor((g+this.mountSeed)/(i?75:140))%P4,d=x+9-kN-Math.round(Math.sin((g+this.mountSeed)/420)*2),f=this.mountSprite??=r.add.sprite(c,d,Xv(E),0).setOrigin(.5,1);f.texture.key!==Xv(E)&&f.setTexture(Xv(E)),f.depth!==S.y-2.5&&f.setDepth(S.y-2.5),f.setFrame(s).setFlipX(n).setPosition(c,d).setVisible(S.visible).setAlpha(this.sprite.alpha);const[l,p]=b.seat[h],v=c-Math.floor(t/2),u=this.sprite.texture,m=Zr(u,`sit/${this.direction}/`);if(m)this.sprite.setFrame(`sit/${this.direction}/${m-1}`);else{const y=Zr(u,`pickup/${this.direction}/`);y&&this.sprite.setFrame(`pickup/${this.direction}/${Math.floor(y/2)}`)}return this.sprite.setPosition(v+(n?t-1-l:l),d-o+p+ON),this.shadowScaled||(this.shadow.setScale(2.4,1.8),this.shadowScaled=!0),!0}
}
