// Generated by scripts/snapshot.mjs from assets/main-BQrz5gkk.js. Do not edit by hand.
export function createWingKit(Phaser) {
  const tt = Phaser;
  const l6 = {divine_wings:{texture:"divine-wings",url:"/wings/divine-wings.png",rootX:.5/26,rootY:26/36,scale:1,far:13150328,drop:0,aura:"gold"},demon_wings:{texture:"demon-wings",url:"/wings/demon-wings.png",rootX:.5/77,rootY:50.5/84,scale:.5,far:11049128,drop:8,aura:"demon",rim:"demon-wings-rim",rimUrl:"/wings/demon-wings-rim.png"}};
  const XG = [16730666,16752704,11555071,16734896];
  const ZE = 16761395;
  const BG = 16771496;
  const Cu = [15764735,9580780];
  const s3 = [16758858,16722996];
  const WG = [[[0,2.3,20,12,5,...Cu],[3.1,1.9,16,14,4,...Cu],[4.7,1.3,30,6,3,...Cu]],[[1.2,2,28,-8,5,...s3],[4.2,2.1,19,12,4,...s3]],[[.5,1.3,34,4,3,...Cu],[3.6,1.1,30,6,2,...Cu]]];
  const Wr = 96;
  function VG(e){return WG.map((i,g)=>{const b=`demon-swirl-${g}`;if(e.textures.exists(b))return b;const w=e.textures.createCanvas(b,Wr,Wr),T=w.getContext(),d=T.createImageData(Wr,Wr),x=Wr/2;for(const[t,r,p,o,a,n,s]of i){const l=Math.ceil(r*(p+Math.abs(o))*2);for(let c=0;c<=l;c++){const h=c/l,m=t+r*h,v=p+o*h+Math.sin(h*13+t*3)*1.6,u=Math.max(1,Math.round(a*(1-h*.75))),f=S=>Math.round((n>>S&255)*(1-h)+(s>>S&255)*h),y=Math.round(x+Math.cos(m)*v),E=Math.round(x+Math.sin(m)*v),M=Math.round(255*(1-h*.45));for(let S=0;S<u;S++)for(let C=0;C<u;C++){const A=y+C-(u>>1),L=E+S-(u>>1);if(A<0||L<0||A>=Wr||L>=Wr)continue;const P=(L*Wr+A)*4;d.data[P+3]>=M||(d.data[P]=f(16),d.data[P+1]=f(8),d.data[P+2]=f(0),d.data[P+3]=M)}}}return T.putImageData(d,0,0),w.refresh(),b})}
  const zG = 10108159;
  const i3 = ["east","south-east","south","south-west","west","north-west","north","north-east"];
  return {
    config: l6,
    directions: i3,
    methods: {
      setWings(i){const g=i?l6[i]:void 0;if(g&&this.wings?.id===i||!g&&!this.wings)return;for(const a of this.wingParts())a.destroy();this.wings=void 0;const b=this.sprite.scene;if(!i||!g||!b.textures.exists(g.texture))return;const w=g.aura==="demon",T=tt.BlendModes.ADD,d=w?tt.BlendModes.NORMAL:T,x=(a=g.texture)=>b.add.sprite(this.x,this.y,a).setOrigin(g.rootX,g.rootY).setVisible(!1),t=()=>[x().setTintFill(w?zG:ZE).setBlendMode(d),x(),w&&g.rim&&b.textures.exists(g.rim)?x(g.rim):x().setBlendMode(T)],r=w?XG:[ZE,BG],p=Array.from({length:w?18:10},(a,n)=>b.add.rectangle(this.x,this.y,n%3?1:2,n%3?1:2,r[n%r.length],1).setBlendMode(d).setVisible(!1)),o=w?VG(b).map(a=>b.add.sprite(this.x,this.y,a).setVisible(!1)):[];this.wings={id:i,style:g,left:t(),right:t(),motes:p,swirls:o,seed:Math.random()*1e3}},
      drawWings(i){const g=this.wings;if(!g)return;const{left:b,right:w,motes:T,swirls:d,style:x}=g,t=i.visible&&!this.dead&&this.sprite.visible;for(const A of this.wingParts())A.setVisible(t);if(!t)return;const r=this.sprite.scene.time.now,p=this.wasWalking,o=x.aura==="demon",a=Math.sin((r+g.seed)/(p?130:420)),n=-.05+a*(p?.18:.07),s=.5+Math.sin((r+g.seed)/520)*.5,l=this.sprite.alpha,c=.5+.5*Math.sin((r+g.seed)/90)*Math.sin((r+g.seed)/53),h=Math.max(0,i3.indexOf(this.direction))*Math.PI/4,m=Math.cos(h),v=Math.sin(h),u=this.sprite.x,f=this.sprite.y-(this.sitting?22:30)+x.drop,y=v<-.3?i.y+10.5:i.y+8,E=o?[1.1+s*.05,1,1]:[1.08+s*.04,1,1],M=o?[.22+s*.16,1,.65+c*.35]:[.3+s*.15,1,s*.12],S=(A,L,P,O,R,I,D,k)=>A.forEach((B,$)=>{const U=E[$]*x.scale;B.setPosition(L,P).setScale(O*U,R*U).setRotation(I).setDepth(D+$*.01).setAlpha(l*k*M[$])});let C;if(Math.abs(v)<.3){const A=m>0?-1:1,L=u+A*(this.sitting?6:3);S(w,L,f,A*.62,1,-n*A,y+.1,1),S(b,L+A,f-2,A*.5,.94,-(n+.08)*A,y,1),b[1].setTint(x.far),C=[[L,f,A,.62],[L+A,f-2,A,.5]]}else{const A=Math.abs(v),L=.45+.55*A,P=Math.round(-m*3),O=Math.round(3+3*A);b[1].setTint(16777215),S(w,u+P+O,f,L,1,-n,y,1),S(b,u+P-O,f,-L,1,n,y,1),C=[[u+P+O,f,1,L],[u+P-O,f,-1,L]]}if(o){const A=this.sprite.y-(this.sitting?18:26);d.forEach((L,P)=>{const O=(P%2?-1:1)*(r+g.seed*7)/[1700,2300,1300][P];L.setPosition(u,A).setRotation(O+P*2.1).setScale(1,.82).setDepth(P===2?i.y+10.6:y-.2).setAlpha(l*(P===2?.25+s*.15:.75+s*.25))}),T.forEach((L,P)=>{const[O,R,I,D]=C[P%2],k=(r/1600+g.seed+P*.29)%1,B=6+P*9%30,$=-30+P*13%34;L.setPosition(Math.round(O+I*(B+k*8)*D),Math.round(R+$-k*22)).setDepth(y+.05).setAlpha(l*Math.sin(k*Math.PI)*(P%3?.7:.5+c*.5))});return}T.forEach((A,L)=>{const[P,O,R,I]=C[L%2],D=(r/1400+g.seed+L*.37)%1,k=8+L*7%20,B=-22+L*11%28;A.setPosition(Math.round(P+R*(k+D*4)*I),Math.round(O+B+D*10)).setDepth(y+.05).setAlpha(l*Math.sin(D*Math.PI)*(.6+s*.4))})},
      wingParts(){const i=this.wings;return i?[...i.left,...i.right,...i.motes,...i.swirls]:[]},
    },
  };
}
