import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";
import typescript from "@rollup/plugin-typescript";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));

function webviewHtml() {
    return {
        name: "webview-html",
        writeBundle() {
            const css = readFileSync(join(root, "webview", "styles.css"), "utf8");
            // The game's own engine, inlined so the sandboxed webview needs no network.
            const phaser = readFileSync(join(root, "node_modules", "phaser", "dist", "phaser.min.js"), "utf8").replaceAll(
                "</script",
                "<\\/script"
            );
            const js = readFileSync(join(root, "dist", "webview.js"), "utf8").replaceAll(
                "</script",
                "<\\/script"
            );
            const html = `<!doctype html><html lang="th"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><style>:root{/*__DRAWDY_STYLING__*/}</style><style id="drawdy-vars"></style><style>${css}</style></head><body><div id="root"></div><script>${phaser}</script><script>${js}</script></body></html>`;
            // Committed because the publishing service builds src/index.ts with
            // esbuild and runs no bundler plugins.
            const out = join(root, "src", "webview-html.ts");
            const source =
                `// Generated by rollup.config.mjs. Do not edit by hand.\n` +
                `export const WEBVIEW_HTML = ${JSON.stringify(html)};\n`;
            // Skipping identical writes keeps the dev server's rebuild-on-change from looping.
            if (!existsSync(out) || readFileSync(out, "utf8") !== source) writeFileSync(out, source);
        },
    };
}

export default [
    {
        input: "webview/main.ts",
        output: { file: "dist/webview.js", format: "iife" },
        // The panel bundles what it imports, such as fflate's deflate for the cards.
        plugins: [nodeResolve({ browser: true }), typescript(), terser(), webviewHtml()],
    },
    {
        input: "src/index.ts",
        output: { file: "dist/main.js", format: "cjs", exports: "named" },
        plugins: [typescript(), terser()],
    },
];
