import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getText, need } from "./lumivara.mjs";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "game", "name-frames.ts");
const CHECK = process.argv.includes("--check");
// The panel lays a frame out from these rules; if the game changes them, the
// layout in webview/nametag.ts has to change with them.
const INSIDE = 13;
const LABEL_RULES = [
    `:root{--nf-inside:${INSIDE}px}`,
    "[data-name-frame]{border-style:solid;border-width:0;padding:0 4px;min-width:2em;line-height:var(--nf-inside);image-rendering:pixelated}",
    "[data-name-frame]:after{content:\"\";position:absolute;left:50%;top:calc(-1 * var(--nf-t));bottom:calc(-1 * var(--nf-b));width:var(--nf-gem-w);transform:translate(-50%);background-position:center;background-size:100% 100%;background-repeat:no-repeat;image-rendering:pixelated;",
    ".world-label[data-name-frame]{margin-top:var(--nf-t)}",
    ".world-label[data-under-frame]{margin-top:var(--nf-h)}",
];

const home = await getText("/");
const stylesheet = need(home.match(/assets\/main-[\w-]+\.css/)?.[0], "main stylesheet");
const css = await getText("/" + stylesheet);
const cosmetics = JSON.parse(await getText("/cosmetics.json"));
for (const rule of LABEL_RULES) {
    if (!css.includes(rule)) throw new Error(`The game's name frame label rule changed in ${stylesheet}; expected ${rule}`);
}

const pxs = (list) => list.trim().split(/\s+/).map((v) => Number(need(v.match(/^([\d.]+)px$/)?.[1], `px length in ${list}`)));
const frames = {};
const urls = {};
for (const [, id, body] of css.matchAll(/\[data-name-frame=([\w-]+)\]\{([^}]*)\}/g)) {
    const image = need(
        body.match(/border-image:url\(([^)]+)\) (\d+) (\d+) (\d+) (\d+) fill\/([^/]+)\/([^/]+) stretch$/),
        `${id} border-image`,
    );
    const [, url, t, r, b, l, width, outset] = image;
    if (pxs(width).join() !== pxs(outset).join()) throw new Error(`${id} has a border-image outset unlike its width`);
    const sizes = need(css.match(new RegExp(`\\[data-name-frame=${id}\\],\\[data-under-frame=${id}\\]\\{([^}]*)\\}`))?.[1], `${id} sizes`);
    const size = (name) => pxs(need(sizes.match(new RegExp(`--nf-${name}:([^;]+)`))?.[1], `${id} --nf-${name}`))[0];
    if (["t", "r", "b", "l"].map(size).join() !== pxs(width).join()) throw new Error(`${id} has --nf sizes unlike its border-image widths`);
    if (size("h") !== size("t") + INSIDE + size("b")) throw new Error(`${id} is not ${INSIDE} px inside`);
    frames[id] = { slice: [t, r, b, l].map(Number), width: pxs(width), gemWidth: size("gem-w") };
    urls[id] = { url, gemUrl: css.match(new RegExp(`\\[data-name-frame=${id}\\]:after\\{background-image:url\\(([^)]+)\\)`))?.[1] };
}
need(Object.keys(frames).length, "name frame rules");

const source =
    `// Generated by scripts/name-frames.mjs from ${stylesheet}. Do not edit by hand.\n` +
    `import type { NameFrameSlices } from "./types";\n\n` +
    `export const NAME_FRAME_SLICES: Record<string, NameFrameSlices> = {\n` +
    Object.entries(frames)
        .map(([id, f]) => `  ${id}: { slice: [${f.slice.join(", ")}], width: [${f.width.join(", ")}], gemWidth: ${f.gemWidth} },\n`)
        .join("") +
    `};\n`;

const liveFrames = cosmetics.skins.filter((s) => s.slot === "nameframe");
const withoutSlices = liveFrames.filter((s) => !frames[s.id]).map((s) => s.id);
const artDiffers = liveFrames
    .filter((s) => urls[s.id] && (s.nameFrame?.url !== urls[s.id].url || s.nameFrame?.gemUrl !== urls[s.id].gemUrl))
    .map((s) => s.id);
if (withoutSlices.length) console.log(`Name frames in cosmetics.json with no rule in the game's stylesheet (the panel leaves them out): ${withoutSlices.join(", ")}`);
if (artDiffers.length) console.log(`Name frame art in cosmetics.json differs from the game's stylesheet (the panel follows cosmetics.json): ${artDiffers.join(", ")}`);

if (CHECK) {
    const body = (text) => text.replace(/^\/\/.*\n/, "");
    if (body(readFileSync(OUT, "utf8")) !== body(source)) {
        console.log(`Name frame slices changed in ${stylesheet}. Run npm run name-frames.`);
        process.exit(1);
    }
    console.log(`Name frame slices are identical to ${stylesheet} (cosmetics.json build ${cosmetics.build}).`);
    process.exit(0);
}
writeFileSync(OUT, source);
console.log(JSON.stringify({ stylesheet, frames: Object.keys(frames) }, null, 1));
