import * as acorn from "acorn";
import * as eslintScope from "eslint-scope";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalCode, getText, need } from "./lumivara.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "game", "riding.game.js");
// --check lifts the code in memory and compares it with the copy in the repo
// instead of writing it.
const CHECK = process.argv.includes("--check");

const analyse = (code) => {
    const ast = acorn.parse(code, { ecmaVersion: "latest", sourceType: "module", ranges: true });
    const scopes = eslintScope.analyze(ast, { ecmaVersion: 2022, sourceType: "module" });
    return { code, ast, scopes, module: scopes.scopes.find((s) => s.type === "module") };
};
const src = (code, node) => code.slice(node.range[0], node.range[1]);

const home = await getText("/");
const mainChunk = need(home.match(/assets\/main-[\w-]+\.js/)?.[0], "main chunk");
const main = analyse(await getText("/" + mainChunk));

let method;
(function walk(node) {
    if (!node || typeof node.type !== "string") return;
    if (node.type === "MethodDefinition" && node.key?.name === "drawRiding") {
        if (method) throw new Error("drawRiding defined twice");
        method = node;
    }
    for (const key of Object.keys(node)) {
        const child = node[key];
        if (Array.isArray(child)) child.forEach(walk);
        else if (child && typeof child.type === "string") walk(child);
    }
})(main.ast);
need(method, "method drawRiding");

const chunks = new Map();
const chunk = async (path) => {
    if (!chunks.has(path)) chunks.set(path, analyse(await getText(new URL(path, `https://x/${mainChunk}`).pathname)));
    return chunks.get(path);
};

// The panel draws riding itself (src/game/riding.ts), so this lifts the game's
// drawRiding and the definition of every module-level name it reads, one level
// deep, to show what changed when the game changes. The mount table is left
// out: cosmetics.json carries it.
const isMountTable = (init) =>
    init?.type === "ObjectExpression" &&
    init.properties.length > 0 &&
    init.properties.every((p) => p.value?.type === "ObjectExpression" && p.value.properties.some((q) => q.key?.name === "seat"));
const definitionOf = (m, variable, name) => {
    const def = need(variable.defs[0], `definition of ${variable.name}`);
    if (def.type === "Variable") {
        if (isMountTable(def.node.init)) return `const ${name} = {}; // the mount table, which cosmetics.json carries`;
        return `const ${name} = ${def.node.init ? src(m.code, def.node.init) : "undefined"};`;
    }
    if (def.type === "FunctionName") return src(m.code, def.node).replace(/^function\s+[\w$]+/, `function ${name}`);
    throw new Error(`${variable.name} is a ${def.type}`);
};

const inside = (node, range) => node.range[0] >= range[0] && node.range[1] <= range[1];
const seen = new Set();
const declarations = [];
const sources = new Set();
for (const ref of main.scopes.scopes.flatMap((s) => s.references)) {
    const variable = ref.resolved;
    if (!inside(ref.identifier, method.range) || variable?.scope !== main.module || seen.has(variable)) continue;
    seen.add(variable);
    const def = need(variable.defs[0], `definition of ${variable.name}`);
    if (def.type !== "ImportBinding") {
        declarations.push(definitionOf(main, variable, variable.name));
        continue;
    }
    const from = def.parent.source.value;
    sources.add(from.replace(/^\.\//, "assets/"));
    const other = await chunk(from);
    const imported = def.node.imported.name ?? def.node.imported.value;
    const local = other.ast.body
        .filter((n) => n.type === "ExportNamedDeclaration" && !n.declaration)
        .flatMap((n) => n.specifiers)
        .find((s) => (s.exported.name ?? s.exported.value) === imported)?.local.name;
    declarations.push(definitionOf(other, need(other.module.set.get(local), `export ${imported} of ${from}`), variable.name));
}

const source =
    `// Generated by scripts/riding-code.mjs from ${[mainChunk, ...sources].join(" and ")}. Do not edit by hand.\n` +
    `// Not bundled: the game's riding code and what it reads, for src/game/riding.ts to follow.\n` +
    declarations.join("\n") +
    `\nclass Rider {\n  ${src(main.code, method)}\n}\n`;

if (CHECK) {
    if (canonicalCode(readFileSync(OUT, "utf8")) !== canonicalCode(source)) {
        console.log(`Riding code changed in ${mainChunk}. Run npm run riding-code and bring src/game/riding.ts in line with the diff.`);
        process.exit(1);
    }
    console.log(`Riding code is identical to ${mainChunk}.`);
    process.exit(0);
}
writeFileSync(OUT, source);
console.log(`Lifted drawRiding and ${declarations.length} definitions from ${mainChunk} into src/game/riding.game.js.`);
